[server]
maxUploadSize = 200
enableCORS = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#1A73E8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"

[runner]
requirementsFile = "./requirements-deploy.txt"
magicEnabled = true 